# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 031b0c433356fd10b964a40452bea6316a417fc5417db311892801368ad5b8140000070489bfa1edbb6a8e536a71dd5c003e6f5df4a20df80569828c06ce04ab

test:
  secret_key_base: 1263d7185962382c0c2158706e0a38fb807d6fef5184ec17c608448f095ddc15b657a00092214d5b9b19f156e5d552ea5f6bbe1c04f8d5ad4e2e936146f297ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
